upload:
  dir: C:\edumanagemnentsystem\src\main\resources\static\img\
spring:

  mvc:
    static-path-pattern: /static/**

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/edumanagement
    username: postgres
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true
  servlet:
    multipart:
      max-request-size: 30MB

server:
  port: 8082

springdoc:
  api-docs:
    path: /api-docs
