spring:
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 30MB
      enabled: true

  mvc:
    static-path-pattern: /static/**

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://edu-db:5432/edumanagement
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true

server:
  port: 8082