spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    static-path-pattern: /static/**

  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://edumanagement.cp7ompjjcxv5.eu-north-1.rds.amazonaws.com/postgres
    username: postgres
    password: edum2022

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true


server:
  port: 5000
  max-http-header-size: 20KB


springdoc:
  api-docs:
    path: /api-docs
